// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLhYL5sapzkNjK-tyvf-XuAkT_YnfrOPY',
    appId: '1:709924201424:web:487eeff6edc622a8ce4fd5',
    messagingSenderId: '709924201424',
    projectId: 'cs310-66b27',
    authDomain: 'cs310-66b27.firebaseapp.com',
    storageBucket: 'cs310-66b27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZNOofHUDbIfptNFAWtusT2TTlZbQnII',
    appId: '1:709924201424:android:fac726cbc1c4e9c1ce4fd5',
    messagingSenderId: '709924201424',
    projectId: 'cs310-66b27',
    storageBucket: 'cs310-66b27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6tPZFgxTaK_gggCGC6JqvXAWufBXp70E',
    appId: '1:709924201424:ios:202d3a899118e801ce4fd5',
    messagingSenderId: '709924201424',
    projectId: 'cs310-66b27',
    storageBucket: 'cs310-66b27.firebasestorage.app',
    iosBundleId: 'com.example.cs310Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6tPZFgxTaK_gggCGC6JqvXAWufBXp70E',
    appId: '1:709924201424:ios:202d3a899118e801ce4fd5',
    messagingSenderId: '709924201424',
    projectId: 'cs310-66b27',
    storageBucket: 'cs310-66b27.firebasestorage.app',
    iosBundleId: 'com.example.cs310Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLhYL5sapzkNjK-tyvf-XuAkT_YnfrOPY',
    appId: '1:709924201424:web:5bf0a2fdeb3213f1ce4fd5',
    messagingSenderId: '709924201424',
    projectId: 'cs310-66b27',
    authDomain: 'cs310-66b27.firebaseapp.com',
    storageBucket: 'cs310-66b27.firebasestorage.app',
  );
}
